/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Authority.Authority;
import Business.ConfigureASystem;
import Business.DB40util.DB4OUtil;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author kshitij
 */
public class MainJFrame extends javax.swing.JFrame {

    private Ecosystem ecosystem;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        ecosystem = dB4OUtil.retrieveSystem();
        // ecosystem = ConfigureASystem.configure();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jSplitPane1 = new javax.swing.JSplitPane();
        loginScreenjPanel = new javax.swing.JPanel();
        loginjButton = new javax.swing.JButton();
        loginScreenjLabel = new javax.swing.JLabel();
        logoutjButton = new javax.swing.JButton();
        usernamejLabel = new javax.swing.JLabel();
        usernamejTextField = new javax.swing.JTextField();
        passwordjLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        companyTypejLabel = new javax.swing.JLabel();
        companyNamejLabel = new javax.swing.JLabel();
        cityNamejLabel = new javax.swing.JLabel();
        personNamejLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        userProcessContainer = new javax.swing.JPanel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        loginScreenjPanel.setBackground(new java.awt.Color(115, 166, 200));
        loginScreenjPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginScreenjPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginScreenjPanel.setFocusable(false);
        loginScreenjPanel.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        loginScreenjPanel.setInheritsPopupMenu(true);

        loginjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        loginjButton.setText("Login");
        loginjButton.setToolTipText("Login");
        loginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButtonActionPerformed(evt);
            }
        });

        loginScreenjLabel.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        loginScreenjLabel.setText("LOGIN SCREEN'");

        logoutjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        logoutjButton.setText("LogOut");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });

        usernamejLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        usernamejLabel.setText("Username");

        usernamejTextField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        usernamejTextField.setPreferredSize(new java.awt.Dimension(8, 39));

        passwordjLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        passwordjLabel.setText("Password");

        PasswordField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        PasswordField.setPreferredSize(new java.awt.Dimension(8, 39));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/image.jpg"))); // NOI18N

        companyTypejLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        companyNamejLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        cityNamejLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        personNamejLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        javax.swing.GroupLayout loginScreenjPanelLayout = new javax.swing.GroupLayout(loginScreenjPanel);
        loginScreenjPanel.setLayout(loginScreenjPanelLayout);
        loginScreenjPanelLayout.setHorizontalGroup(
            loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenjPanelLayout.createSequentialGroup()
                .addGroup(loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginScreenjPanelLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addGroup(loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernamejLabel)
                            .addGroup(loginScreenjPanelLayout.createSequentialGroup()
                                .addGroup(loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(logoutjButton)
                                    .addComponent(passwordjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(loginScreenjPanelLayout.createSequentialGroup()
                                        .addGap(154, 154, 154)
                                        .addComponent(loginjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(loginScreenjPanelLayout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addGroup(loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(loginScreenjLabel))
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(companyTypejLabel)
                    .addComponent(companyNamejLabel)
                    .addComponent(cityNamejLabel)
                    .addComponent(personNamejLabel))
                .addGap(487, 487, 487))
        );
        loginScreenjPanelLayout.setVerticalGroup(
            loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenjPanelLayout.createSequentialGroup()
                .addGroup(loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginScreenjPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginScreenjPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(usernamejLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginScreenjLabel)
                .addGap(8, 8, 8)
                .addGroup(loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordjLabel))
                .addGap(57, 57, 57)
                .addGroup(loginScreenjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutjButton)
                    .addComponent(loginjButton))
                .addGap(38, 38, 38))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(loginScreenjPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(companyTypejLabel)
                .addGap(67, 67, 67)
                .addComponent(companyNamejLabel)
                .addGap(78, 78, 78)
                .addComponent(cityNamejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(personNamejLabel)
                .addGap(9, 9, 9))
        );

        jSplitPane1.setTopComponent(loginScreenjPanel);

        jPanel2.setBackground(new java.awt.Color(152, 163, 165));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.CardLayout());

        jSplitPane2.setBackground(new java.awt.Color(206, 208, 209));
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));
        jSplitPane2.setLeftComponent(jPanel3);

        userProcessContainer.setBackground(new java.awt.Color(115, 166, 200));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(userProcessContainer);

        jPanel2.add(jSplitPane2, "card2");

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        userProcessContainer.removeAll();
        usernamejTextField.setText(null);
        PasswordField.setText(null);

//        companyNamejLabel.setText(null);
//        companyTypejLabel.setText(null);
//        cityNamejLabel.setText(null);
//        personNamejLabel.setText(null);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_logoutjButtonActionPerformed

    private void loginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButtonActionPerformed
        String username = usernamejTextField.getText();
        char[] secPassword = PasswordField.getPassword();
        String password = String.valueOf(secPassword);

        UserAccount ua = ecosystem.getUserAccountDirectory().authenticateUserLogin(username, password);
        Organization organization = null;
        Enterprise enterprise = null;
        Authority authority = null;
        if (ua == null) {
            Authority authority1 = ecosystem.getAuthority();
            ua = authority1.getUserAccountDirectory().authenticateUserLogin(username, password);
            if (ua != null) {
                authority = authority1;
            }
            if (ua == null) {
                for (Network network : ecosystem.getNetworkLst()) {
                    for (Enterprise enterprise1 : network.getEnterpriseDirectory().getEnterpriseList()) {
                        ua = enterprise1.getUserAccountDirectory().authenticateUserLogin(username, password);
                        if (ua == null) {
                            for (Organization organization1 : enterprise1.getOrganizationDirectory().getOrganizationList()) {
                                ua = organization1.getUserAccountDirectory().authenticateUserLogin(username, password);
                                if (ua != null) {
                                    enterprise = enterprise1;
                                    organization = organization1;
                                    break;
                                }
                            }
                        } else {
                            enterprise = enterprise1;
                            break;
                        }
                        if (organization != null) {
                            break;
                        }
                    }
                    if (enterprise != null) {
                        break;
                    }
                }
            }
        }

        if (ua == null) {
            JOptionPane.showMessageDialog(null, "Sorry! Invalid credentials");
            return;
        }
        userProcessContainer.add("workArea", ua.getRole().createWorkArea(userProcessContainer,
                ua, organization, enterprise, ecosystem, authority));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

//        if (username.equals("admin")) {
//            return;
//        } else {
//            companyNamejLabel.setText(enterprise.getName());
//            companyTypejLabel.setText(enterprise.getEnterpriseType().getValue());
//            cityNamejLabel.setText(enterprise.getLocation().getCity());
//            personNamejLabel.setText(ua.getPerson().getName());
//        }
    }//GEN-LAST:event_loginjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel cityNamejLabel;
    private javax.swing.JLabel companyNamejLabel;
    private javax.swing.JLabel companyTypejLabel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel loginScreenjLabel;
    private javax.swing.JPanel loginScreenjPanel;
    private javax.swing.JButton loginjButton;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JLabel personNamejLabel;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JLabel usernamejLabel;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables
}
