/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageEnterprise;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class ManageNetworkEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private Ecosystem ecosystem;

    /**
     * Creates new form CreateCityEnterpriseJPanel
     */
    public ManageNetworkEnterpriseJPanel(JPanel upc, Ecosystem ecosystem) {
        initComponents();
        this.upc = upc;
        this.ecosystem = ecosystem;
        populateCityComboBox();
    }

    private void populateCityComboBox() {
        cityNamejComboBox1.removeAllItems();
        for (Network network : ecosystem.getNetworkLst()) {
            cityNamejComboBox1.addItem(network);
            populatEntNameTable(network);
        }
    }

    private void populatEntNameTable(Network network) {
        DefaultTableModel model = (DefaultTableModel) entpTypeNamejTable.getModel();
        model.setRowCount(0);
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[4];
                row[0] = enterprise.getEnterpriseType().getValue();
                row[1] = enterprise;
                row[2] = enterprise.getOrgId();
                row[3] = enterprise.getLocation().getCity();
                model.addRow(row);
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entpTypeNamejTable = new javax.swing.JTable();
        cityNamejLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        removejButton = new javax.swing.JButton();
        refreshjButton = new javax.swing.JButton();
        createEnterprisejButton = new javax.swing.JButton();
        updatejButton = new javax.swing.JButton();
        cityNamejComboBox1 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        entpTypeNamejTable.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        entpTypeNamejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Type", "Enterprise Name", "Enterprise Id", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        entpTypeNamejTable.setPreferredSize(new java.awt.Dimension(300, 300));
        entpTypeNamejTable.setRowHeight(26);
        jScrollPane1.setViewportView(entpTypeNamejTable);
        if (entpTypeNamejTable.getColumnModel().getColumnCount() > 0) {
            entpTypeNamejTable.getColumnModel().getColumn(0).setResizable(false);
            entpTypeNamejTable.getColumnModel().getColumn(1).setResizable(false);
        }

        cityNamejLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        cityNamejLabel.setText("Network Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel2.setText("ENTERPRISE TYPE AND LIST");

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        removejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        removejButton.setText("Remove");
        removejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removejButtonActionPerformed(evt);
            }
        });

        refreshjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        createEnterprisejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        createEnterprisejButton.setText("Create Enterprise");
        createEnterprisejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEnterprisejButtonActionPerformed(evt);
            }
        });

        updatejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        cityNamejComboBox1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        cityNamejComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityNamejComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cityNamejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cityNamejComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton1)
                        .addGap(101, 101, 101)
                        .addComponent(updatejButton)
                        .addGap(139, 139, 139)
                        .addComponent(refreshjButton)
                        .addGap(161, 161, 161)
                        .addComponent(removejButton)
                        .addGap(154, 154, 154)
                        .addComponent(createEnterprisejButton)))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cityNamejComboBox1)
                    .addComponent(cityNamejLabel)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(updatejButton)
                    .addComponent(refreshjButton)
                    .addComponent(removejButton)
                    .addComponent(createEnterprisejButton))
                .addContainerGap(226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void removejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removejButtonActionPerformed
        int selectedRow = entpTypeNamejTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to remove");
            return;
        }
        Enterprise enterprise  = (Enterprise) entpTypeNamejTable.getValueAt(selectedRow, 1);
        for(Network network : ecosystem.getNetworkLst()) {
            network.getEnterpriseDirectory().getEnterpriseList().remove(enterprise);
        }
        Network network = (Network) cityNamejComboBox1.getSelectedItem();
        populatEntNameTable(network);
    }//GEN-LAST:event_removejButtonActionPerformed

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
        Network network = (Network) cityNamejComboBox1.getSelectedItem();
        populatEntNameTable(network);
    }//GEN-LAST:event_refreshjButtonActionPerformed

    private void cityNamejComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityNamejComboBox1ActionPerformed
        Network network = (Network) cityNamejComboBox1.getSelectedItem();
        populatEntNameTable(network);
    }//GEN-LAST:event_cityNamejComboBox1ActionPerformed

    private void createEnterprisejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEnterprisejButtonActionPerformed
        CreateEnterprise panel = new CreateEnterprise(upc, ecosystem);
        upc.add("CreateAuth", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_createEnterprisejButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
       int selectedRow = entpTypeNamejTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to remove");
            return;
        }
        Enterprise enterprise  = (Enterprise) entpTypeNamejTable.getValueAt(selectedRow, 1);
        UpdateEnterpriseJPanel panel = new UpdateEnterpriseJPanel(upc, enterprise);
        upc.add("CreateAuth", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_updatejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cityNamejComboBox1;
    private javax.swing.JLabel cityNamejLabel;
    private javax.swing.JButton createEnterprisejButton;
    private javax.swing.JTable entpTypeNamejTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JButton removejButton;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
