/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.PatientArea;

import Business.Drug.Drug;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Patient.MedicalHistory.VitalSignCheck;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.DoctorPatientDrugIssueReq;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class DrugResponseJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private UserAccount ua;
    private Enterprise enterprise;
    private Ecosystem ecosystem;

    /**
     * Creates new form DrugResponseJPanel
     */
    public DrugResponseJPanel(JPanel upc, UserAccount ua, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.ua = ua;
        this.upc = upc;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        populateDrugComboBox();
    }

    private void populateAllDrugIssueTable(Drug drug3) {
        DefaultTableModel model = (DefaultTableModel) allmedicineissuejTable.getModel();
        model.setRowCount(0);
        for (WorkRequest wr2 : drug3.getWorkQueue().getWorkRequestList()) {
            if (wr2 instanceof DoctorPatientDrugIssueReq) {
                DoctorPatientDrugIssueReq dp = (DoctorPatientDrugIssueReq) wr2;
                if (dp.getSender().getUsername().equals(ua.getUsername())) {
                    Object[] row = new Object[10];
                    row[0] = dp.getReqId();
                    row[1] = drug3.getDrugName();
                    row[2] = drug3;
                    row[3] = drug3.getDisease().getDiseaseName();
                    row[4] = dp.getSender().getPerson().getName();
                    row[5] = dp.getSafetyIssue();
                    row[6] = drug3.getPharmaceuticalName();
                    row[7] = dp.getCallBack() == null ? ("No") : (dp.getCallBack());
                    row[8] = dp;
                    row[9] = dp.gettDate();
                    model.addRow(row);
                    
                }
            }
        }
    }

    private void populateDrugComboBox() {
        drugNamejComboBox.removeAllItems();
        Patient patient = (Patient) ua.getPerson();
        for (VitalSignCheck vsc : patient.getVitalCheckHistory().getVitalCheckList()) {
            drugNamejComboBox.addItem(vsc.getDrug());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        allmedicineissuejTable = new javax.swing.JTable();
        viewIssueListjButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        issuejTextArea = new javax.swing.JTextArea();
        sedIssuejButton = new javax.swing.JButton();
        drugNamejComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(115, 166, 200));

        allmedicineissuejTable.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        allmedicineissuejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Medicine Name", "Medicine Code", "Disease Cure", "Sender", "Safety Issues", "Pharmaceutical Name", "CallBack", "Status", "timstamp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allmedicineissuejTable.setRowHeight(26);
        jScrollPane1.setViewportView(allmedicineissuejTable);

        viewIssueListjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        viewIssueListjButton.setText("Refresh");
        viewIssueListjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewIssueListjButtonActionPerformed(evt);
            }
        });

        issuejTextArea.setColumns(20);
        issuejTextArea.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        issuejTextArea.setRows(5);
        jScrollPane4.setViewportView(issuejTextArea);

        sedIssuejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        sedIssuejButton.setText("Send Issue");
        sedIssuejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedIssuejButtonActionPerformed(evt);
            }
        });

        drugNamejComboBox.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        drugNamejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugNamejComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel5.setText("DRUG ISSUES");

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel1.setText("Drugs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(67, 67, 67)
                        .addComponent(drugNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(336, 336, 336)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(backjButton)
                        .addGap(157, 157, 157)
                        .addComponent(viewIssueListjButton)
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(sedIssuejButton)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(drugNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewIssueListjButton)
                        .addComponent(backjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(sedIssuejButton)))
                .addContainerGap(456, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewIssueListjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewIssueListjButtonActionPerformed
        Drug druga = (Drug) drugNamejComboBox.getSelectedItem();
        if (druga != null) {
            populateAllDrugIssueTable(druga);
        }
    }//GEN-LAST:event_viewIssueListjButtonActionPerformed

    private void sedIssuejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedIssuejButtonActionPerformed
        String issue = issuejTextArea.getText();
        if (issue.equals("") || issue == null) {
            JOptionPane.showMessageDialog(null, "Please enter the concern regarding the drug");
            return;
        }
        Drug drug2 = (Drug) drugNamejComboBox.getSelectedItem();
        
        if(drug2 == null) {
            JOptionPane.showMessageDialog(null, "Please select a drug to send an issue");
            return;
        }
       
        DoctorPatientDrugIssueReq dpdi = new DoctorPatientDrugIssueReq();

        dpdi.setSender(ua);
        dpdi.setSafetyIssue(issue);
        dpdi.setStatus("Sent");
        dpdi.setOrganizationCity(enterprise.getLocation().getCity());
        dpdi.setOrganizationId(enterprise.getOrganizationID());
        dpdi.setOrganizationName(enterprise.getName());
        dpdi.setCallBack("waiting");

        for (Drug drug1 : ecosystem.getDrugDirectory().getDrugList()) {
            if (drug2.getDrugId() == drug1.getDrugId()) {
                drug1.getWorkQueue().getWorkRequestList().add(dpdi);
            }
        }
        Drug druga = (Drug) drugNamejComboBox.getSelectedItem();
        if (druga != null) {
            populateAllDrugIssueTable(druga);
        }
    }//GEN-LAST:event_sedIssuejButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void drugNamejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugNamejComboBoxActionPerformed
        Drug druga = (Drug) drugNamejComboBox.getSelectedItem();
        if (druga != null) {
            populateAllDrugIssueTable(druga);
        }
    }//GEN-LAST:event_drugNamejComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allmedicineissuejTable;
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox drugNamejComboBox;
    private javax.swing.JTextArea issuejTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton sedIssuejButton;
    private javax.swing.JButton viewIssueListjButton;
    // End of variables declaration//GEN-END:variables
}
