/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.PatientArea;

import Business.Organization.Organization;
import Business.Patient.MedicalHistory.VitalSignCheck;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class PatientHistoryCheckJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private Patient patient;
    private Organization org;
    private UserAccount ua;

    /**
     * Creates new form PatientMedicalHistoryJPanel
     */
    public PatientHistoryCheckJPanel(JPanel upc, Patient patient, Organization org, UserAccount ua) {
        initComponents();
        this.upc = upc;
        this.patient = patient;
        this.org = org;
        this.ua = ua;
        populatePatientMedHistory();
    }

    private void populatePatientMedHistory() {
        DefaultTableModel model = (DefaultTableModel) medicalHistoryTablejTable.getModel();
        model.setRowCount(0);

        for (VitalSignCheck vsc : patient.getVitalCheckHistory().getVitalCheckList()) {
            Object[] row = new Object[9];
            row[0] = vsc;
            row[1] = vsc.getDisease().getDiseaseName();
            row[2] = vsc.getDisease().getSymptoms();
            row[3] = vsc.getDrug().getDrugName() == null? ("N/A") :  vsc.getDrug().getDrugName();
            row[4] = vsc.getAttendantName();
            row[5] = vsc.getAttendantId();
            row[6] = vsc.getHealthCareName();
            row[7] = vsc.getDateAttended();
            row[8] = vsc.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        medicalHistoryTablejTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        medicalHistoryTablejTable.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        medicalHistoryTablejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vital Id", "Disease", "Symptoms", "Medication", "DOC/Nurse", "Doc/Nurse Id", "Hosp/Clinic", "Date Attended", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        medicalHistoryTablejTable.setRowHeight(26);
        jScrollPane1.setViewportView(medicalHistoryTablejTable);
        if (medicalHistoryTablejTable.getColumnModel().getColumnCount() > 0) {
            medicalHistoryTablejTable.getColumnModel().getColumn(0).setResizable(false);
            medicalHistoryTablejTable.getColumnModel().getColumn(1).setResizable(false);
            medicalHistoryTablejTable.getColumnModel().getColumn(2).setResizable(false);
            medicalHistoryTablejTable.getColumnModel().getColumn(3).setResizable(false);
            medicalHistoryTablejTable.getColumnModel().getColumn(4).setResizable(false);
            medicalHistoryTablejTable.getColumnModel().getColumn(5).setResizable(false);
            medicalHistoryTablejTable.getColumnModel().getColumn(6).setResizable(false);
            medicalHistoryTablejTable.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel1.setText("PATIENT MEDICAL HISTORY");

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addComponent(backjButton)))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(backjButton)
                .addContainerGap(287, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);
    }//GEN-LAST:event_backjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicalHistoryTablejTable;
    // End of variables declaration//GEN-END:variables
}
