/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.PatientArea;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class PersonalInfoJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private Ecosystem ecosystem;
    private UserAccount ua;
    private Organization org;
    private Patient patient;
    private Enterprise enterprise;

    /**
     * Creates new form PatientCheckupJPanel
     */
    public PersonalInfoJPanel(JPanel upc, Ecosystem ecosystem, UserAccount ua, Organization org, Enterprise enterprise) {
        initComponents();
        this.upc = upc;
        this.ua = ua;
        this.org = org;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        populatePatientData();
        
    }
                      
        
        private void populatePatientData() {
        DefaultTableModel model = (DefaultTableModel) patientInformationjTable.getModel();
        model.setRowCount(0);
        patient = (Patient) ua.getPerson();
        Object[] row = new Object[4];
        row[0] = patient;
        row[1] = patient.getPatientId();
        row[2] = patient.getAge();
        row[3] = patient.getSex();
        model.addRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        patientInformationjTable = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();
        patientInformationjLabel = new javax.swing.JLabel();
        myMedicalHistoryjButton = new javax.swing.JButton();
        changePasswordjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        patientInformationjTable.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        patientInformationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Patient ID", "Age", "Sex"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientInformationjTable.setRowHeight(26);
        jScrollPane1.setViewportView(patientInformationjTable);
        if (patientInformationjTable.getColumnModel().getColumnCount() > 0) {
            patientInformationjTable.getColumnModel().getColumn(0).setResizable(false);
            patientInformationjTable.getColumnModel().getColumn(1).setResizable(false);
            patientInformationjTable.getColumnModel().getColumn(2).setResizable(false);
            patientInformationjTable.getColumnModel().getColumn(3).setResizable(false);
        }

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        patientInformationjLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        patientInformationjLabel.setText("PATIENT INFORMATION");

        myMedicalHistoryjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        myMedicalHistoryjButton.setText("My Medical History");
        myMedicalHistoryjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myMedicalHistoryjButtonActionPerformed(evt);
            }
        });

        changePasswordjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        changePasswordjButton.setText("Change Password");
        changePasswordjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(597, 597, 597)
                        .addComponent(patientInformationjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(backjButton)
                        .addGap(391, 391, 391)
                        .addComponent(changePasswordjButton)
                        .addGap(308, 308, 308)
                        .addComponent(myMedicalHistoryjButton)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(patientInformationjLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePasswordjButton)
                    .addComponent(myMedicalHistoryjButton)
                    .addComponent(backjButton))
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myMedicalHistoryjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myMedicalHistoryjButtonActionPerformed

        if(patient!= null){   
        PatientHistoryCheckJPanel panel = new PatientHistoryCheckJPanel(upc, patient, org, ua);
        upc.add("Patientcheckup", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
        }
    }//GEN-LAST:event_myMedicalHistoryjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void changePasswordjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordjButtonActionPerformed
            ChangePasswordJPanel panel = new ChangePasswordJPanel(upc, ua);
            upc.add("CreateAuth", panel);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
    }//GEN-LAST:event_changePasswordjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JButton changePasswordjButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton myMedicalHistoryjButton;
    private javax.swing.JLabel patientInformationjLabel;
    private javax.swing.JTable patientInformationjTable;
    // End of variables declaration//GEN-END:variables
}
