/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.PatientArea;

import Business.Drug.Drug;
import Business.Ecosystem;
import Business.Patient.MedicalHistory.VitalSignCheck;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.PatientToPatient;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kshitij
 */
public class SimilarPatientsJPanel extends javax.swing.JPanel {
    
    private Ecosystem ecosystem;
    private JPanel upc;
    private UserAccount ua;

    /**
     * Creates new form PatientsLikeMeJPanel
     */
    public SimilarPatientsJPanel(JPanel upc, Ecosystem ecosystem, UserAccount ua) {
        initComponents();
        this.upc = upc;
        this.ecosystem = ecosystem;
        this.ua = ua;
        populateDrugName();
    }
    
    
    private void populateDrugName(){
        drugNamejComboBox.removeAllItems();
        for(Drug drug : ecosystem.getDrugDirectory().getDrugList()){
            if(drug.getStatus() == null) {
                
            }
            if(drug.getStatus().equals("Approved")){
            drugNamejComboBox.addItem(drug);
            }
        }
    }
    
    public void populatePatientList(Drug drug) {
        patientListjComboBox.removeAllItems();
        for (Patient patient : ecosystem.getPersonDirectory().getPatientDirectory().getPatientList()) {
            Patient patient1 = (Patient) ua.getPerson();
            if(ua.getPerson() instanceof Patient){
            if(patient.getPatientId() != patient1.getPatientId()){
            for (VitalSignCheck vsc : patient.getVitalCheckHistory().getVitalCheckList()) {
                if (vsc.getDrug().getDrugName().equals(drug.getDrugName())) {
                    patientListjComboBox.addItem(patient);
                         }
                     }
                }
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        drugNamejComboBox = new javax.swing.JComboBox();
        patientListjComboBox = new javax.swing.JComboBox();
        sendjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterMessagejTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel1.setText("PATIENT INTERACTION");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel2.setText("Drug  Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel3.setText("Patient List");

        drugNamejComboBox.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        drugNamejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugNamejComboBoxActionPerformed(evt);
            }
        });

        patientListjComboBox.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        sendjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        sendjButton.setText("Send Message");
        sendjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendjButtonActionPerformed(evt);
            }
        });

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel4.setText("Message");

        enterMessagejTextArea.setColumns(20);
        enterMessagejTextArea.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        enterMessagejTextArea.setRows(5);
        jScrollPane1.setViewportView(enterMessagejTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(backjButton))
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientListjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drugNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(jLabel1)))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(drugNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(patientListjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel4)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton)
                    .addComponent(sendjButton))
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void drugNamejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugNamejComboBoxActionPerformed
        Drug drug = (Drug) drugNamejComboBox.getSelectedItem();
        if (drug != null) {
            populatePatientList(drug);
        }
    }//GEN-LAST:event_drugNamejComboBoxActionPerformed

    private void sendjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendjButtonActionPerformed
        Drug drug = (Drug) drugNamejComboBox.getSelectedItem();
        Patient patient = (Patient) patientListjComboBox.getSelectedItem();
        String message =  enterMessagejTextArea.getText();
        
        if(drug == null || patient == null || message.equals("") || message == null){
            JOptionPane.showMessageDialog(null, "Please fill all the values before sending a message");
            return;
        }
        PatientToPatient ptop = new PatientToPatient();
        ptop.setSender(ua);
        ptop.setMessage(message);
        patient.getWorkQueue().getWorkRequestList().add(ptop);
    }//GEN-LAST:event_sendjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox drugNamejComboBox;
    private javax.swing.JTextArea enterMessagejTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox patientListjComboBox;
    private javax.swing.JButton sendjButton;
    // End of variables declaration//GEN-END:variables
}
