/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.DoctorArea;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kshitij
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel upc;
    private Ecosystem ecosystem;
    private UserAccount ua;
    private Organization org;
    private Enterprise enterprise;
    /**
     * Creates new form DoctorWorkAreaJPanelJPanel
     */
    public DoctorWorkAreaJPanel(JPanel upc, Ecosystem ecosystem, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.upc = upc;
        this.ecosystem = ecosystem;
        this.ua = account;
        this.enterprise = enterprise;
        this.org = organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        patientCheckupjButton = new javax.swing.JButton();
        drugResponsejButton = new javax.swing.JButton();
        forwardPatientjButton = new javax.swing.JButton();
        receivePatientInfojButton = new javax.swing.JButton();
        referredPAtientReqestsjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel1.setText("DOCTOR WORK AREA");

        patientCheckupjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        patientCheckupjButton.setText("Patient Checkup");
        patientCheckupjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientCheckupjButtonActionPerformed(evt);
            }
        });

        drugResponsejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        drugResponsejButton.setText("Drug Response");
        drugResponsejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugResponsejButtonActionPerformed(evt);
            }
        });

        forwardPatientjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        forwardPatientjButton.setText("Forward Patient Request");
        forwardPatientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardPatientjButtonActionPerformed(evt);
            }
        });

        receivePatientInfojButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        receivePatientInfojButton.setText("Receive Patient Info");
        receivePatientInfojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivePatientInfojButtonActionPerformed(evt);
            }
        });

        referredPAtientReqestsjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        referredPAtientReqestsjButton.setText("Referred Patient Requests");
        referredPAtientReqestsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referredPAtientReqestsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(drugResponsejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patientCheckupjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forwardPatientjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(receivePatientInfojButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(referredPAtientReqestsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(108, 108, 108)
                .addComponent(patientCheckupjButton)
                .addGap(101, 101, 101)
                .addComponent(drugResponsejButton)
                .addGap(112, 112, 112)
                .addComponent(forwardPatientjButton)
                .addGap(121, 121, 121)
                .addComponent(receivePatientInfojButton)
                .addGap(103, 103, 103)
                .addComponent(referredPAtientReqestsjButton)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientCheckupjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientCheckupjButtonActionPerformed
        PatientCheckupJPanel panel = new PatientCheckupJPanel(upc,ecosystem, ua, org, enterprise);
        upc.add("Patientcheckup", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_patientCheckupjButtonActionPerformed

    private void drugResponsejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugResponsejButtonActionPerformed
        DrugResponseJPanel panel = new DrugResponseJPanel(upc,ecosystem, ua, enterprise);
        upc.add("DocWorkReq", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_drugResponsejButtonActionPerformed

    private void forwardPatientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardPatientjButtonActionPerformed
        ForwardPatientRequestJPanel panel = new ForwardPatientRequestJPanel(upc, ua, enterprise, ecosystem);
        upc.add("For", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_forwardPatientjButtonActionPerformed

    private void receivePatientInfojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivePatientInfojButtonActionPerformed
         ReceivePatientInfoJPanel panel = new ReceivePatientInfoJPanel(upc, ua, enterprise, ecosystem);
        upc.add("DocWorkReq", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_receivePatientInfojButtonActionPerformed

    private void referredPAtientReqestsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referredPAtientReqestsjButtonActionPerformed
         ReferredPatientRequestJPane panel = new ReferredPatientRequestJPane(upc, ua, enterprise, ecosystem);
        upc.add("DocWorkReq", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_referredPAtientReqestsjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drugResponsejButton;
    private javax.swing.JButton forwardPatientjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton patientCheckupjButton;
    private javax.swing.JButton receivePatientInfojButton;
    private javax.swing.JButton referredPAtientReqestsjButton;
    // End of variables declaration//GEN-END:variables
}
