/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.DoctorArea;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.DoctorToNurse;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class NurseTaskReportJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private UserAccount ua;
    private Enterprise enterprise;
    private Patient patient;
    private Date date;

    /**
     * Creates new form NurseTaskReportJPanel
     */
    public NurseTaskReportJPanel(JPanel upc, UserAccount ua, Enterprise enterprise, Patient patient) {
        initComponents();
        this.ua = ua;
        this.upc = upc;
        this.enterprise = enterprise;
        this.patient = patient;
        populateNurseRequestTable();
    }

    private void populateNurseRequestTable() {
        DefaultTableModel model = (DefaultTableModel) nurseRequestjTable1.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : patient.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof DoctorToNurse) {
                DoctorToNurse dtn = (DoctorToNurse) wr;
                Object[] row = new Object[6];
                row[0] = dtn.getPatient();
                row[1] = dtn.getInstDoc();
                row[2] = dtn.getSender().getPerson().getName();
                row[3] = dtn.getReceiver() == null ? ("N/A") : dtn.getReceiver().getPerson().getName();
                row[4] = dtn;
                row[5] = dtn.getDate();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nurseRequestjTable1 = new javax.swing.JTable();
        reqestjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        instructionsjTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(115, 166, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel1.setText("NURSE TASK REPORT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel2.setText("Instructions ");

        nurseRequestjTable1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        nurseRequestjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Instructions", "Primary Doctor", "Receiver", "Status", "Timestamp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nurseRequestjTable1.setRowHeight(26);
        jScrollPane1.setViewportView(nurseRequestjTable1);

        reqestjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        reqestjButton.setText("Send Request");
        reqestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqestjButtonActionPerformed(evt);
            }
        });

        instructionsjTextArea.setColumns(20);
        instructionsjTextArea.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        instructionsjTextArea.setRows(5);
        jScrollPane2.setViewportView(instructionsjTextArea);

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jButton1.setText("View Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(reqestjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(backjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(144, 144, 144)
                .addComponent(jButton1)
                .addContainerGap(174, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(493, 493, 493)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(backjButton))
                        .addGap(66, 66, 66)
                        .addComponent(reqestjButton)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void reqestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqestjButtonActionPerformed
        String inst = instructionsjTextArea.getText().trim();
        if (inst.equals("") || inst == null) {
            JOptionPane.showMessageDialog(null, "Please enter the data in the instruction section.");
            return;
        }
        DoctorToNurse dtn = new DoctorToNurse();
        dtn.setPatient(patient);
        dtn.setSender(ua);
        dtn.setStatus("sent");
        dtn.setInstDoc(inst);
        
        date = new Date();
        dtn.setDate(date);

        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (Organization.Type.Nurse.getValue() == "Nurse Organization") {
                org.getWorkQueue().getWorkRequestList().add(dtn);
            }
        }
        patient.getWorkQueue().getWorkRequestList().add(dtn);
        populateNurseRequestTable();

    }//GEN-LAST:event_reqestjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = nurseRequestjTable1.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        DoctorToNurse dtn = (DoctorToNurse) nurseRequestjTable1.getValueAt(selectedRow, 4);
        ViewNurseTreatmentJPanel panel = new ViewNurseTreatmentJPanel(upc, dtn);
        upc.add("DocWorkReq", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JTextArea instructionsjTextArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable nurseRequestjTable1;
    private javax.swing.JButton reqestjButton;
    // End of variables declaration//GEN-END:variables
}
