/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.DoctorArea;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.DoctorToDoctor;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class ReferredPatientRequestJPane extends javax.swing.JPanel {
    private JPanel upc;
    private UserAccount ua;
    private Enterprise enterprise;
    private Ecosystem ecosystem;
    /**
     * Creates new form ReferredPatientRequestJPane
     */
    public ReferredPatientRequestJPane(JPanel upc, UserAccount ua, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.upc = upc;
        this.enterprise = enterprise;
        this.ua = ua;
        this.ecosystem = ecosystem;
        populateReferredPatList();
    }
    
    private void populateReferredPatList(){
         DefaultTableModel model = (DefaultTableModel) referredPatientListjTable.getModel();
         model.setRowCount(0);
         
         Employee doctor = (Employee) ua.getPerson();
         for(WorkRequest wr : doctor.getWorkQueue().getWorkRequestList()){
             if(wr instanceof DoctorToDoctor){
                 DoctorToDoctor dtds = (DoctorToDoctor) wr;
                 Object[] row = new Object[6];
                 row[0] = dtds.getPatient();
                 row[1] = dtds.getPatient().getPatientId();
                 row[2] = dtds.getSender().getPerson().getName();
                 row[3] = dtds.getHealthCareName();
                 row[4] = dtds;
                 row[5] =dtds.getDate();
                 model.addRow(row);
             }
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        referredPatientListjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        patientMedicalHistoryjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(115, 166, 200));

        referredPatientListjTable.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        referredPatientListjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient NAme", "Patient Id", "Referred By", "HealthCare Name", "status", "Timestamp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        referredPatientListjTable.setRowHeight(26);
        jScrollPane1.setViewportView(referredPatientListjTable);

        jLabel1.setText("Referred Patients List");

        patientMedicalHistoryjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        patientMedicalHistoryjButton.setText("Patient Medical History");
        patientMedicalHistoryjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientMedicalHistoryjButtonActionPerformed(evt);
            }
        });

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(545, 545, 545)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(backjButton)
                        .addGap(515, 515, 515)
                        .addComponent(patientMedicalHistoryjButton)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton)
                    .addComponent(patientMedicalHistoryjButton))
                .addContainerGap(391, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientMedicalHistoryjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientMedicalHistoryjButtonActionPerformed
        int selectedRow = referredPatientListjTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row to proceed further");
            return;
        }
        Patient patient = (Patient) referredPatientListjTable.getValueAt(selectedRow, 0);
        DoctorToDoctor dtds = (DoctorToDoctor) referredPatientListjTable.getValueAt(selectedRow, 4);
        dtds.setStatus("Patient Checked");
        if (patient != null) {
            PatientMedicalHistoryJPanel panel = new PatientMedicalHistoryJPanel(upc, patient, ua, enterprise, ecosystem);
            upc.add("Patientcheckup", panel);
            CardLayout layout = (CardLayout) upc.getLayout();
            layout.next(upc);
        }
    }//GEN-LAST:event_patientMedicalHistoryjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton patientMedicalHistoryjButton;
    private javax.swing.JTable referredPatientListjTable;
    // End of variables declaration//GEN-END:variables
}
