/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Pharmacy.SalesPersonArea;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kshitij
 */
public class SalesPersonWorkArea extends javax.swing.JPanel {
        private JPanel upc;
        private Enterprise enterprise;
        private UserAccount ua;
        private Organization org; 
        private Ecosystem ecosystem;
    /**
     * Creates new form SalesPersonWorkArea
     */
    public SalesPersonWorkArea(JPanel upc, UserAccount ua, Organization organization, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.upc = upc;
        this.enterprise = enterprise;
        this.ua = ua;
        this.org = organization;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageMedicinesjButton = new javax.swing.JButton();
        manageWorkRequestsjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(115, 166, 200));

        manageMedicinesjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        manageMedicinesjButton.setText("Manage Medicines");
        manageMedicinesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMedicinesjButtonActionPerformed(evt);
            }
        });

        manageWorkRequestsjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        manageWorkRequestsjButton.setText("Manage Prescribed Drug Patients");
        manageWorkRequestsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWorkRequestsjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel1.setText("SALES PERSON WORK AREA");

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jButton1.setText("Medicine Review");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageMedicinesjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageWorkRequestsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(114, 114, 114)
                .addComponent(manageWorkRequestsjButton)
                .addGap(108, 108, 108)
                .addComponent(manageMedicinesjButton)
                .addGap(108, 108, 108)
                .addComponent(jButton1)
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageMedicinesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMedicinesjButtonActionPerformed
        ManageMedicinesJPanel panel = new ManageMedicinesJPanel(upc, ua, enterprise, ecosystem);
          upc.add("CreateAuth", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
           
    }//GEN-LAST:event_manageMedicinesjButtonActionPerformed

    private void manageWorkRequestsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWorkRequestsjButtonActionPerformed
        ManageSalesReqJPanel panel = new ManageSalesReqJPanel(upc, ua, enterprise, ecosystem);
        upc.add("SalesReq", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageWorkRequestsjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MedicineReviewJPanel panel = new MedicineReviewJPanel(upc, ua, enterprise, ecosystem);
        upc.add("SalesReq", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageMedicinesjButton;
    private javax.swing.JButton manageWorkRequestsjButton;
    // End of variables declaration//GEN-END:variables
}
