/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageUserAccounts;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Role.ClinicAdminRole;
import Business.Role.HospitalAdminRole;
import Business.Role.PatientRole;
import Business.Role.PharmaceuticalAdminRole;
import Business.Role.PharmacyAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class ManageEnterpriseAdminUserAccountJPanel extends javax.swing.JPanel {

    private Ecosystem ecosystem;
    private JPanel upc;

    /**
     * Creates new form CreateEnterpriseAdminAccountJPanel
     */
    public ManageEnterpriseAdminUserAccountJPanel(JPanel upc, Ecosystem ecosystem) {
        initComponents();
        this.upc = upc;
        this.ecosystem = ecosystem;
        populateCityComboBox();

    }

    private void populateCityComboBox() {
        cityNamejComboBox.removeAllItems();
        for (Network network : ecosystem.getNetworkLst()) {
            if(network!= null){
            cityNamejComboBox.addItem(network);
            populateAdminDetailsTable(network);
        }
        }
    }

    private void populateEnterpriseNameComboBox() {
        enterpriseNamejComboBox.removeAllItems();
        Network network = (Network) cityNamejComboBox.getSelectedItem();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            enterpriseNamejComboBox.addItem(enterprise);
            populateAdminDetailsTable(network);
        }

    }

    private void populateAdminDetailsTable(Network network) {
        DefaultTableModel model = (DefaultTableModel) adminDetailsjTable.getModel();
        model.setRowCount(0);
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
               if(!(ua.getRole() instanceof PatientRole)){
                Object[] row = new Object[5];
                row[0] = enterprise.getName();
                row[1] = ua;
                row[2] = ua.getPerson().getPersonId();
                row[3] = ua.getUsername();
                row[4] = ua.getPassword();
                model.addRow(row);
               }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adminDetailsjTable = new javax.swing.JTable();
        enterpriseNamejLabel = new javax.swing.JLabel();
        enterpriseNamejComboBox = new javax.swing.JComboBox();
        adminNamejLabel = new javax.swing.JLabel();
        userNamejLabel = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();
        userNamejTextField = new javax.swing.JTextField();
        passwordjTextField = new javax.swing.JTextField();
        adminNamejTextField = new javax.swing.JTextField();
        createAdminjButton = new javax.swing.JButton();
        removejButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cityNamejComboBox = new javax.swing.JComboBox();
        cityjLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        streetLine1jTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        streetLine2jTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        statejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        zipCodejTextField = new javax.swing.JTextField();
        refreshjButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        adminDetailsjTable.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        adminDetailsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Admin Name", "Admin Id", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adminDetailsjTable.setRowHeight(26);
        jScrollPane1.setViewportView(adminDetailsjTable);
        if (adminDetailsjTable.getColumnModel().getColumnCount() > 0) {
            adminDetailsjTable.getColumnModel().getColumn(0).setResizable(false);
            adminDetailsjTable.getColumnModel().getColumn(1).setResizable(false);
            adminDetailsjTable.getColumnModel().getColumn(2).setResizable(false);
            adminDetailsjTable.getColumnModel().getColumn(3).setResizable(false);
            adminDetailsjTable.getColumnModel().getColumn(4).setResizable(false);
        }

        enterpriseNamejLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        enterpriseNamejLabel.setText("Enterprise Name");

        enterpriseNamejComboBox.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        enterpriseNamejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseNamejComboBoxActionPerformed(evt);
            }
        });

        adminNamejLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        adminNamejLabel.setText("Admin Name");

        userNamejLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        userNamejLabel.setText("Username");

        passwordjLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        passwordjLabel.setText("Password");

        userNamejTextField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        passwordjTextField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        passwordjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordjTextFieldActionPerformed(evt);
            }
        });

        adminNamejTextField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        adminNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNamejTextFieldActionPerformed(evt);
            }
        });

        createAdminjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        createAdminjButton.setText("Create Admin");
        createAdminjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdminjButtonActionPerformed(evt);
            }
        });

        removejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        removejButton.setText("Remove");
        removejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removejButtonActionPerformed(evt);
            }
        });

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel1.setText("MANAGE ENTERPRISE ADMIN");

        cityNamejComboBox.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        cityNamejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityNamejComboBoxActionPerformed(evt);
            }
        });

        cityjLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        cityjLabel.setText("City : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel2.setText("Street Line1");

        streetLine1jTextField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel6.setText("Street Line2");

        streetLine2jTextField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel5.setText("City");

        cityjTextField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel7.setText("State");

        statejTextField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel8.setText("Zip Code");

        zipCodejTextField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        refreshjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel3.setText("Login Details");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel4.setText("Address Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cityjLabel)
                        .addGap(89, 89, 89)
                        .addComponent(cityNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(userNamejLabel)
                                                .addGap(190, 190, 190)
                                                .addComponent(userNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(streetLine1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zipCodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel8))
                                .addGap(185, 185, 185)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createAdminjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(statejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(2, 2, 2)
                                                    .addComponent(passwordjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(63, 63, 63)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(streetLine2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(passwordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(removejButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backjButton)
                                .addGap(395, 395, 395)
                                .addComponent(refreshjButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(adminNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(adminNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(enterpriseNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(93, 93, 93)
                                    .addComponent(enterpriseNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityjLabel)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backjButton)
                            .addComponent(refreshjButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(removejButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNamejLabel)
                    .addComponent(enterpriseNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminNamejLabel)
                    .addComponent(adminNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNamejLabel)
                    .addComponent(userNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordjLabel)
                    .addComponent(passwordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jLabel4)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(streetLine1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(streetLine2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(zipCodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(createAdminjButton)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNamejTextFieldActionPerformed

    private void cityNamejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityNamejComboBoxActionPerformed
        populateEnterpriseNameComboBox();
        Network network = (Network) cityNamejComboBox.getSelectedItem();
        populateAdminDetailsTable(network);
    }//GEN-LAST:event_cityNamejComboBoxActionPerformed

    private void createAdminjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAdminjButtonActionPerformed
        Network network = (Network) cityNamejComboBox.getSelectedItem();
        Enterprise enterprise = (Enterprise) enterpriseNamejComboBox.getSelectedItem();
        String username = userNamejTextField.getText().trim();
        String password = passwordjTextField.getText().trim();
        String adminName = adminNamejTextField.getText().trim();
        String street1 = streetLine1jTextField.getText().trim();
        String street2 = streetLine2jTextField.getText().trim();
        String city = cityjTextField.getText().trim();
        String state = statejTextField.getText().trim();
        String zipcode = zipCodejTextField.getText().trim();
        if (network == null || enterprise == null || username.equals("") ||username==null|| password.equals("")||password== null
                || adminName.equals("")||adminName == null || street1.equals("") || street1==null  ||  city.equals("")|| city ==null
                || state.equals("") || zipcode.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the details to create admin account");
            return;
        }
        String validName = ecosystem.getUcd().validUsernameCheck(username);
        if (validName == (null)) {
            JOptionPane.showMessageDialog(null, "Username already taken, please enter a different username.");
            return;
        }

        Employee employee = enterprise.getPersonDirectory().getEmployeeDirectory().createEmployee(adminName, street1,
                street2, city, state, zipcode);
        if (enterprise.getEnterpriseType().getValue().equals("Hospital")) {
            UserAccount userAccount = enterprise.getUserAccountDirectory().createUserAccount(username,
                    password, employee, new HospitalAdminRole());
        } else if (enterprise.getEnterpriseType().getValue().equals("Clinic")) {
            UserAccount userAccount = enterprise.getUserAccountDirectory().createUserAccount(username,
                    password, employee, new ClinicAdminRole());
        } else if (enterprise.getEnterpriseType().getValue().equals("Pharmacy")) {
            UserAccount userAccount = enterprise.getUserAccountDirectory().createUserAccount(username,
                    password, employee, new PharmacyAdminRole());
        } else {
            UserAccount userAccount = enterprise.getUserAccountDirectory().createUserAccount(username,
                    password, employee, new PharmaceuticalAdminRole());
        }
        populateAdminDetailsTable(network);
        ecosystem.getUcd().addUsername(username);


    }//GEN-LAST:event_createAdminjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void removejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removejButtonActionPerformed
        int selectedRow = adminDetailsjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to remove");
        }
        UserAccount ua = (UserAccount) adminDetailsjTable.getValueAt(selectedRow, 1);
        for (Network network : ecosystem.getNetworkLst()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                enterprise.getUserAccountDirectory().getUserAccountList().remove(ua);
                Network network1 = (Network) cityNamejComboBox.getSelectedItem();
                populateAdminDetailsTable(network1);

            }
        }
    }//GEN-LAST:event_removejButtonActionPerformed

    private void enterpriseNamejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseNamejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseNamejComboBoxActionPerformed

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
        Network network = (Network) cityNamejComboBox.getSelectedItem();
        populateAdminDetailsTable(network);
    }//GEN-LAST:event_refreshjButtonActionPerformed

    private void passwordjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminDetailsjTable;
    private javax.swing.JLabel adminNamejLabel;
    private javax.swing.JTextField adminNamejTextField;
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox cityNamejComboBox;
    private javax.swing.JLabel cityjLabel;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JButton createAdminjButton;
    private javax.swing.JComboBox enterpriseNamejComboBox;
    private javax.swing.JLabel enterpriseNamejLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JTextField passwordjTextField;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JButton removejButton;
    private javax.swing.JTextField statejTextField;
    private javax.swing.JTextField streetLine1jTextField;
    private javax.swing.JTextField streetLine2jTextField;
    private javax.swing.JLabel userNamejLabel;
    private javax.swing.JTextField userNamejTextField;
    private javax.swing.JTextField zipCodejTextField;
    // End of variables declaration//GEN-END:variables
}
