/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.NurseArea;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.DoctorToNurse;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class DoctorOrderJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private UserAccount ua;
    private Organization organization;
  
    
    /**
     * Creates new form DoctorOrderJPanel
     */
    public DoctorOrderJPanel(JPanel upc, Organization organization, UserAccount ua) {
        initComponents();
        this.organization = organization;
        this.upc = upc;
        this.ua = ua;
        populatePatientTable();
    }

    private void populatePatientTable() {
        DefaultTableModel model = (DefaultTableModel) patientTablejTable1.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof DoctorToNurse) {
                DoctorToNurse dtn = (DoctorToNurse) wr;
                Object[] row = new Object[10];
                row[0] = dtn.getReqId();
                row[1] = dtn.getPatient().getName();
                row[2] = dtn.getInjectionName() == null? ("N/A") : dtn.getInjectionName();
                row[3] = dtn.getDoseLevel();
                row[4] = dtn.getComplexities() == null? ("N/A") : dtn.getComplexities();
                row[5] = dtn.getSender().getPerson().getName();
                row[6] = dtn.getReceiver() == null? ("N/A") : dtn.getReceiver().getPerson().getName();
                row[7] = dtn;
                row[8] = dtn.getInstDoc();
                row[9] = dtn.getDate();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTablejTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dosagejTextField = new javax.swing.JTextField();
        injectionjTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        refreshjButton = new javax.swing.JButton();
        assignjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        complicationjTextArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(115, 166, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel1.setText("PATIENT DOCTOR REQUESTED");

        patientTablejTable1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        patientTablejTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Id", "Patient Named", "Injection Name", "Dosage", "Complications", "Sender", "Receiver", "Status", "Doc Instn", "Timestamp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientTablejTable1.setRowHeight(26);
        jScrollPane1.setViewportView(patientTablejTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel2.setText("Injection");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel3.setText("Dosage");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel4.setText("Complications");

        dosagejTextField.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        injectionjTextField3.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        refreshjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        assignjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        assignjButton.setText("Assign ");
        assignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignjButtonActionPerformed(evt);
            }
        });

        complicationjTextArea.setColumns(20);
        complicationjTextArea.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        complicationjTextArea.setRows(5);
        jScrollPane2.setViewportView(complicationjTextArea);

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel7.setText("mg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jLabel1)
                .addContainerGap(714, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assignjButton)
                    .addComponent(backjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(injectionjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(216, 216, 216)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dosagejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(297, 297, 297))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(refreshjButton)
                                .addGap(279, 279, 279))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshjButton)
                    .addComponent(assignjButton))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(injectionjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dosagejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(backjButton))
                .addGap(79, 79, 79))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
        populatePatientTable();
    }//GEN-LAST:event_refreshjButtonActionPerformed

    private void assignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignjButtonActionPerformed
        int selectedRow = patientTablejTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to assign to you");
            return;
        }
        
        DoctorToNurse dtn =  (DoctorToNurse) patientTablejTable1.getValueAt(selectedRow, 7);

        if(dtn.getStatus().equals("Completed")){
            JOptionPane.showMessageDialog(null, "Patient request has already been sent.");
            return;
        }
        dtn.setReceiver(ua);
        dtn.setStatus("In-Progress");
        populatePatientTable();

        if(dtn.getReceiver() == null){
            JOptionPane.showMessageDialog(null, "Please assign the request to you first");
            return;
        }
    }//GEN-LAST:event_assignjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           int selectedRow = patientTablejTable1.getSelectedRow();
        if(selectedRow < 0) {
           JOptionPane.showMessageDialog(null, "Please select a row first ");
           return;
        }
        
        String inj = injectionjTextField3.getText().trim();
        String comp = complicationjTextArea.getText().trim();
        int dosage;
        try {
            dosage = Integer.parseInt(dosagejTextField.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter correct value");
              return;      
        }
               if (inj == null || inj.equals("")|| comp == null || dosage < 0) {
            JOptionPane.showMessageDialog(null, "Please enter some correct value");
            return;
        }

        DoctorToNurse dtn =  (DoctorToNurse) patientTablejTable1.getValueAt(selectedRow, 7);

        
 
       if (dtn.getStatus().equals("sent")) {
            JOptionPane.showMessageDialog(null, "Please assign the patient request to you first");
            return;                             
        }           
         if(dtn.getStatus().equals("Completed")){
             JOptionPane.showMessageDialog(null, "Patient data has already been sent");
             return;
         }   
         
         dtn.setInjectionName(inj);
         dtn.setDoseLevel(dosage);
         dtn.setComplexities(comp);
         dtn.setStatus("Completed");
         
         
        JOptionPane.showMessageDialog(null, "Patient data added and sent");
        populatePatientTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextArea complicationjTextArea;
    private javax.swing.JTextField dosagejTextField;
    private javax.swing.JTextField injectionjTextField3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable patientTablejTable1;
    private javax.swing.JButton refreshjButton;
    // End of variables declaration//GEN-END:variables
}
