/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.AdminArea;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private Enterprise enterprise;
    private JPanel upc;
    private Ecosystem ecosystem;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel(JPanel upc, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.upc = upc;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        populateOrganizationTable();
        populateOrganizationComboBox();

    }

    private void populateOrganizationComboBox() {
        organizationOptionjComboBox.removeAllItems();
        for (Type type : Organization.Type.values()) {
            if ((type.equals(Type.Doctor)) || (type.equals(Type.Lab))|| (type.equals(Type.Nurse))) {
                organizationOptionjComboBox.addItem(type);
            }
        }
    }

    private void populateOrganizationTable() {
        DefaultTableModel model = (DefaultTableModel) organizationjTable.getModel();
        model.setRowCount(0);
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            Object[] row = new Object[3];
            row[0] = enterprise.getName();
            row[1] = organization;
            row[2] = organization.getOrganizationID();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageOrganizationjLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationjTable = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();
        organizationOptionsjLabel = new javax.swing.JLabel();
        organizationOptionjComboBox = new javax.swing.JComboBox();
        addOrganizationjButton = new javax.swing.JButton();
        removejButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        manageOrganizationjLabel.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        manageOrganizationjLabel.setText("MANAGE ORGANIZATION");

        organizationjTable.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        organizationjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Organization Name", "Organization ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        organizationjTable.setRowHeight(26);
        jScrollPane1.setViewportView(organizationjTable);
        if (organizationjTable.getColumnModel().getColumnCount() > 0) {
            organizationjTable.getColumnModel().getColumn(0).setResizable(false);
            organizationjTable.getColumnModel().getColumn(1).setResizable(false);
            organizationjTable.getColumnModel().getColumn(2).setResizable(false);
        }

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        organizationOptionsjLabel.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        organizationOptionsjLabel.setText("Organization Options");

        organizationOptionjComboBox.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        organizationOptionjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationOptionjComboBoxActionPerformed(evt);
            }
        });

        addOrganizationjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        addOrganizationjButton.setText("Add Organization");
        addOrganizationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizationjButtonActionPerformed(evt);
            }
        });

        removejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        removejButton.setText("Remove");
        removejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backjButton)
                            .addComponent(organizationOptionsjLabel))
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addOrganizationjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removejButton)
                            .addComponent(organizationOptionjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(manageOrganizationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageOrganizationjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removejButton)
                    .addComponent(backjButton))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(organizationOptionsjLabel)
                    .addComponent(organizationOptionjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(addOrganizationjButton)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addOrganizationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizationjButtonActionPerformed
        Type type = (Type) organizationOptionjComboBox.getSelectedItem();
        if (type == null) {
            JOptionPane.showMessageDialog(null, "Please select an valid organization");
            return;
        }
        Boolean result = enterprise.getOrganizationDirectory().searchIfPresent(type);
        if(result == true){
            JOptionPane.showMessageDialog(null, "Organization already added in the enterprise");
            return;
        }

        enterprise.getOrganizationDirectory().addOrganization(type);
        populateOrganizationTable();

    }//GEN-LAST:event_addOrganizationjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void removejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removejButtonActionPerformed
        int selectedRow = organizationjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to remove");
            return;
        }
        Organization organization = (Organization) organizationjTable.getValueAt(selectedRow, 1);
        enterprise.getOrganizationDirectory().getOrganizationList().remove(organization);
        populateOrganizationTable();
    }//GEN-LAST:event_removejButtonActionPerformed

    private void organizationOptionjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationOptionjComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationOptionjComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrganizationjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageOrganizationjLabel;
    private javax.swing.JComboBox organizationOptionjComboBox;
    private javax.swing.JLabel organizationOptionsjLabel;
    private javax.swing.JTable organizationjTable;
    private javax.swing.JButton removejButton;
    // End of variables declaration//GEN-END:variables
}
