/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.AdminArea;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Role;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class ManageEmployeesJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private Enterprise enterprise;
    private DefaultTableModel model;

    /**
     * Creates new form ManageEmployeesJPanel
     */
    public ManageEmployeesJPanel(JPanel upc, Enterprise enterprise) {
        initComponents();
        this.upc = upc;
        this.enterprise = enterprise;
        populateOrganizationComboBox2();
    }

    private void populateEmployeeTable(Organization organization) {
        model = (DefaultTableModel) employeejTable.getModel();
        model.setRowCount(0);

        for (Employee employee : organization.getPersonDirectory().getEmployeeDirectory().getEmployerList()) {
            Object[] row = new Object[4];
            row[0] = organization;
            row[1] = employee;
            row[2] = employee.getPersonId();
            row[3] = employee.getLocation().getCity();
            model.addRow(row);
        }
    }

    private void populateOrganizationComboBox2() {
        organizationOptionjComboBox.removeAllItems();
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            organizationOptionjComboBox.addItem(org);
            populateEmployeeTable(org);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeejTable = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();
        removejButton = new javax.swing.JButton();
        organizationOptionjComboBox = new javax.swing.JComboBox();
        createEmployeejButton = new javax.swing.JButton();
        refreshbutton = new javax.swing.JButton();
        updatejButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel1.setText("MANAGE EMPLOYEE DATA");

        employeejTable.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        employeejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Name", "Employee Name", "Employee ID", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeejTable.setRowHeight(26);
        jScrollPane1.setViewportView(employeejTable);
        if (employeejTable.getColumnModel().getColumnCount() > 0) {
            employeejTable.getColumnModel().getColumn(0).setResizable(false);
            employeejTable.getColumnModel().getColumn(1).setResizable(false);
            employeejTable.getColumnModel().getColumn(2).setResizable(false);
            employeejTable.getColumnModel().getColumn(3).setResizable(false);
        }

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        removejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        removejButton.setText("Remove");
        removejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removejButtonActionPerformed(evt);
            }
        });

        organizationOptionjComboBox.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        organizationOptionjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationOptionjComboBoxActionPerformed(evt);
            }
        });

        createEmployeejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        createEmployeejButton.setText("Create Employee");
        createEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeejButtonActionPerformed(evt);
            }
        });

        refreshbutton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        refreshbutton.setText("Refresh");
        refreshbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbuttonActionPerformed(evt);
            }
        });

        updatejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel2.setText("Organization");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(backjButton)
                        .addGap(157, 157, 157)
                        .addComponent(updatejButton)
                        .addGap(148, 148, 148)
                        .addComponent(refreshbutton)
                        .addGap(169, 169, 169)
                        .addComponent(createEmployeejButton)
                        .addGap(136, 136, 136)
                        .addComponent(removejButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addGap(125, 125, 125)
                        .addComponent(organizationOptionjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(organizationOptionjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton)
                    .addComponent(updatejButton)
                    .addComponent(refreshbutton)
                    .addComponent(createEmployeejButton)
                    .addComponent(removejButton))
                .addContainerGap(435, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);

    }//GEN-LAST:event_backjButtonActionPerformed

    private void organizationOptionjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationOptionjComboBoxActionPerformed
        Organization organization = (Organization) organizationOptionjComboBox.getSelectedItem();
        if (organization != null) {
            populateEmployeeTable(organization);
        }
    }//GEN-LAST:event_organizationOptionjComboBoxActionPerformed

    private void createEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeejButtonActionPerformed
        CreateEmployee panel = new CreateEmployee(upc, enterprise);
        upc.add("CreateAuth", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_createEmployeejButtonActionPerformed

    private void refreshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbuttonActionPerformed
        Organization organization = (Organization) organizationOptionjComboBox.getSelectedItem();
        if (organization != null) {
            populateEmployeeTable(organization);
        }
    }//GEN-LAST:event_refreshbuttonActionPerformed

    private void removejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removejButtonActionPerformed
        Organization org = null;
        int selectedRow = employeejTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to remove");
            return;
        }
        Employee employee = (Employee) employeejTable.getValueAt(selectedRow, 1);
        for (Organization org1 : enterprise.getOrganizationDirectory().getOrganizationList()) {
            org1.getPersonDirectory().getEmployeeDirectory().getEmployerList().remove(employee);
            org = org1;
        }
        populateEmployeeTable(org);
    }//GEN-LAST:event_removejButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        int selectedRow = employeejTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to remove");
            return;
        }
        Employee emp = (Employee) employeejTable.getValueAt(selectedRow, 1);
        UpdateEmployeeData panel = new UpdateEmployeeData(upc, emp);
        upc.add("CreateAuth", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_updatejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JButton createEmployeejButton;
    private javax.swing.JTable employeejTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationOptionjComboBox;
    private javax.swing.JButton refreshbutton;
    private javax.swing.JButton removejButton;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
