/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.AdminArea;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class ManageUserAccount extends javax.swing.JPanel {
    
    private JPanel upc;
    private OrganizationDirectory orgDir;
    private Ecosystem ecosystem;

    /**
     * Creates new form ManageEmployeesJPanel
     */
    public ManageUserAccount(JPanel upc, OrganizationDirectory orgDir, Ecosystem ecosystem) {
        initComponents();
        this.upc = upc;
        this.orgDir = orgDir;
        this.ecosystem = ecosystem;
        populateOrganizationComboBox2();
    }
    
    private void populateEmployeeTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) userAccountjTable.getModel();
        model.setRowCount(0);
        
       
            for(UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()){
            Object[] row = new Object[5];
            row[0] = ua;
            row[1] = ua.getPerson().getPersonId();
            row[2] = ua.getRole();
            row[3] = ua.getUsername();
            row[4] = ua.getPassword();
            model.addRow(row);
            }
        }   
    
    
    
    private void populateOrganizationComboBox2() {
        organizationOptionjComboBox.removeAllItems();
        for (Organization org : orgDir.getOrganizationList()) {
            organizationOptionjComboBox.addItem(org);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userAccountjTable = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();
        removejButton = new javax.swing.JButton();
        organizationOptionjComboBox = new javax.swing.JComboBox();
        createEmployeejButton = new javax.swing.JButton();
        refreshbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel1.setText("MANAGE USER ACCOUNT");

        userAccountjTable.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        userAccountjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "Employee ID", "Employee Role", "username", "password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userAccountjTable.setRowHeight(26);
        jScrollPane1.setViewportView(userAccountjTable);
        if (userAccountjTable.getColumnModel().getColumnCount() > 0) {
            userAccountjTable.getColumnModel().getColumn(0).setResizable(false);
            userAccountjTable.getColumnModel().getColumn(1).setResizable(false);
            userAccountjTable.getColumnModel().getColumn(2).setResizable(false);
            userAccountjTable.getColumnModel().getColumn(3).setResizable(false);
            userAccountjTable.getColumnModel().getColumn(4).setResizable(false);
        }

        backjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        removejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        removejButton.setText("Remove");
        removejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removejButtonActionPerformed(evt);
            }
        });

        organizationOptionjComboBox.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        organizationOptionjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationOptionjComboBoxActionPerformed(evt);
            }
        });

        createEmployeejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        createEmployeejButton.setText("Create User Account");
        createEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeejButtonActionPerformed(evt);
            }
        });

        refreshbutton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        refreshbutton.setText("Refresh");
        refreshbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel2.setText("Organization");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2)
                        .addGap(102, 102, 102)
                        .addComponent(organizationOptionjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(backjButton)
                        .addGap(187, 187, 187)
                        .addComponent(refreshbutton)
                        .addGap(185, 185, 185)
                        .addComponent(createEmployeejButton)
                        .addGap(189, 189, 189)
                        .addComponent(removejButton)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(organizationOptionjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removejButton)
                    .addComponent(createEmployeejButton)
                    .addComponent(refreshbutton)
                    .addComponent(backjButton))
                .addContainerGap(277, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
         upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);
              
    }//GEN-LAST:event_backjButtonActionPerformed

    private void organizationOptionjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationOptionjComboBoxActionPerformed
         Organization organization = (Organization)organizationOptionjComboBox.getSelectedItem();
        if (organization != null){
            populateEmployeeTable(organization);
        }
    }//GEN-LAST:event_organizationOptionjComboBoxActionPerformed

    private void createEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeejButtonActionPerformed
        CreateUserAccount panel = new CreateUserAccount(upc, orgDir, ecosystem);
        upc.add("CreateAuth", panel);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_createEmployeejButtonActionPerformed

    private void refreshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbuttonActionPerformed
       Organization organization = (Organization) organizationOptionjComboBox.getSelectedItem();
        if (organization != null){
        populateEmployeeTable(organization);
        }
    }//GEN-LAST:event_refreshbuttonActionPerformed

    private void removejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removejButtonActionPerformed
        int selectedRow = userAccountjTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to remove");
            return;
        }
        UserAccount ua = (UserAccount) userAccountjTable.getValueAt(selectedRow, 0);
        for(Organization org : orgDir.getOrganizationList()){
            org.getUserAccountDirectory().getUserAccountList().remove(ua);
        }
    }//GEN-LAST:event_removejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JButton createEmployeejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationOptionjComboBox;
    private javax.swing.JButton refreshbutton;
    private javax.swing.JButton removejButton;
    private javax.swing.JTable userAccountjTable;
    // End of variables declaration//GEN-END:variables
}
