/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.AdminArea;

import Business.Location.Location;
import Business.Patient.Patient;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kshitij
 */
public class UpdatePatientDataJPanel extends javax.swing.JPanel {

    private JPanel upc;
    private Patient patient;

    /**
     * Creates new form UpdatePatientDataJPanel
     */
    public UpdatePatientDataJPanel(JPanel upc, Patient patient) {
        initComponents();
        this.upc = upc;
        this.patient = patient;
        showData();

    }

    private void showData() {
        patientNamejTextField.setText(patient.getName());
        patientAgejTextField.setText(String.valueOf(patient.getAge()));
        patientSexjTextField.setText(patient.getSex());
        patientEmailjTextField.setText(patient.getEmailId());
        patientDOBjTextField.setText(patient.getDob());
        street1jTextField.setText(patient.getLocation().getStreetLine1());
        street2jTextField.setText(patient.getLocation().getStreetLine2());
        cityjTextField.setText(patient.getLocation().getCity());
        statejTextField.setText(patient.getLocation().getState());
        zipCodejTextField.setText(patient.getLocation().getZipCode());

        patientNamejTextField.setEnabled(false);
        patientAgejTextField.setEnabled(false);
        patientSexjTextField.setEnabled(false);
        patientEmailjTextField.setEnabled(false);
        patientDOBjTextField.setEnabled(false);
        street1jTextField.setEnabled(false);
        street2jTextField.setEnabled(false);
        cityjTextField.setEnabled(false);
        statejTextField.setEnabled(false);
        zipCodejTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        patientNamejTextField = new javax.swing.JTextField();
        patientAgejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        patientSexjTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        patientEmailjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        patientDOBjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        street1jTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        street2jTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        statejTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        zipCodejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        savejButton = new javax.swing.JButton();
        updatejButton = new javax.swing.JButton();
        backjButto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel3.setText("Patient Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel4.setText("Patient Age");

        patientNamejTextField.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N

        patientAgejTextField.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel5.setText("Patient Sex");

        patientSexjTextField.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel8.setText("Patient Email");

        patientEmailjTextField.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel7.setText("Patient DOB");

        patientDOBjTextField.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel9.setText("Street1");

        street1jTextField.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel10.setText("Street 2");

        street2jTextField.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel11.setText("City");

        cityjTextField.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel12.setText("State");

        statejTextField.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel13.setText("Zip Code");

        zipCodejTextField.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel1.setText("UPDATE PATIENT INFORMATION");

        savejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        savejButton.setText("Save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        updatejButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        backjButto.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        backjButto.setText("<<Back");
        backjButto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtoActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(115, 166, 200));
        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 29)); // NOI18N
        jLabel2.setText("Personal Information");

        jLabel6.setBackground(new java.awt.Color(115, 166, 200));
        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 29)); // NOI18N
        jLabel6.setText("Address Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(backjButto)))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(street1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientDOBjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipCodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(209, 209, 209)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(savejButton)
                            .addGap(384, 384, 384)
                            .addComponent(updatejButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(patientNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(patientSexjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(198, 198, 198)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel8)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(19, 19, 19)))
                            .addGap(141, 141, 141)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(patientEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(patientAgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(street2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(statejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientAgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(patientNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(patientSexjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientEmailjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(patientDOBjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(street1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(street2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(zipCodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(statejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatejButton)
                    .addComponent(savejButton)
                    .addComponent(backjButto))
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        String name = patientNamejTextField.getText();
        int age = 0;
        try {
            age = Integer.parseInt(patientAgejTextField.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter correct age format");
            return;
        }
        String sex = patientSexjTextField.getText();
        String email = patientEmailjTextField.getText();
        String dob = patientDOBjTextField.getText();
        String street1 = street1jTextField.getText();
        String street2 = street2jTextField.getText();
        String city = cityjTextField.getText();
        String state = statejTextField.getText();
        String zip = zipCodejTextField.getText();

        if (name.equals("") || age == 0 || sex.equals("") || dob.equals("")) {
            JOptionPane.showMessageDialog(null, "name, age, sex and dob fields are mandatory");
            return;
        }

        patient.setName(name);
        patient.setSex(sex);
        patient.setEmailId(email);
        patient.setAge(age);
        patient.setDob(dob);
        Location loc = patient.getLocation();
        loc.setStreetLine1(street1);
        loc.setStreetLine2(street2);
        loc.setCity(city);
        loc.setState(state);
        loc.setZipCode(zip);
        patient.setLocation(loc);


    }//GEN-LAST:event_savejButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        patientNamejTextField.setEnabled(true);
        patientAgejTextField.setEnabled(true);
        patientSexjTextField.setEnabled(true);
        patientEmailjTextField.setEnabled(true);
        patientDOBjTextField.setEnabled(true);
        street1jTextField.setEnabled(true);
        street2jTextField.setEnabled(true);
        cityjTextField.setEnabled(true);
        statejTextField.setEnabled(true);
        zipCodejTextField.setEnabled(true);
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void backjButtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtoActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);
    }//GEN-LAST:event_backjButtoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButto;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField patientAgejTextField;
    private javax.swing.JTextField patientDOBjTextField;
    private javax.swing.JTextField patientEmailjTextField;
    private javax.swing.JTextField patientNamejTextField;
    private javax.swing.JTextField patientSexjTextField;
    private javax.swing.JButton savejButton;
    private javax.swing.JTextField statejTextField;
    private javax.swing.JTextField street1jTextField;
    private javax.swing.JTextField street2jTextField;
    private javax.swing.JButton updatejButton;
    private javax.swing.JTextField zipCodejTextField;
    // End of variables declaration//GEN-END:variables
}
