/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.AdminArea;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Patient.Patient;
import Business.WorkRequest.AskforPatientRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kshitij
 */
public class ViewSearchedPatient extends javax.swing.JPanel {
    private Patient patient;
    private JPanel upc;
    private AskforPatientRequest afp;
    private Enterprise enterprise;
    /**
     * Creates new form ViewSearchedPatient
     */
    public ViewSearchedPatient(JPanel upc, Patient patient, AskforPatientRequest afp, Enterprise enterprise) {
        initComponents();
        this.upc = upc;
        this.patient = patient;
        this.afp = afp;
        this.enterprise = enterprise;
        populateSearchPatientData();
    }
    
     public ViewSearchedPatient(JPanel upc, Patient patient) {
        initComponents();
        this.upc = upc;
        this.patient = patient;
        populateSearchPatientData();
     }
    
    private void populateSearchPatientData() {
        DefaultTableModel model = (DefaultTableModel) searchedPatientDatajTable.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[7];
        row[0] = patient;
        row[1] = patient.getSex();
        row[2] = patient.getAge();
        row[3] = patient.getPatientId();
        row[4] = patient.getLocation().getCity();
        row[5] = patient.getPrimaryDoc();
        row[6] = patient.getPrimaryDocId();
        model.addRow(row); 
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        searchedPatientDatajTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sendToDocjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(115, 166, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchedPatientDatajTable.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        searchedPatientDatajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Patient Sex", "Patient Age", "Patient ID", "patient location", "Primary Doc", "Primary Doc Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchedPatientDatajTable.setRowHeight(26);
        jScrollPane1.setViewportView(searchedPatientDatajTable);

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        jLabel1.setText("PATIENT INFORMATION PANEL");

        sendToDocjButton.setFont(new java.awt.Font("Tahoma", 2, 27)); // NOI18N
        sendToDocjButton.setText("Send To Doc");
        sendToDocjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToDocjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jLabel1)
                .addContainerGap(692, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(sendToDocjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(479, 479, 479))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(sendToDocjButton)))
                .addContainerGap(416, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        upc.remove(this);
        CardLayout cardLayout = (CardLayout) upc.getLayout();
        cardLayout.previous(upc);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sendToDocjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToDocjButtonActionPerformed
        afp.setPatient(patient);
        int selectedRow = searchedPatientDatajTable.getSelectedRow();
//        if(selectedRow < 0) {
//            JOptionPane.showMessageDialog(null, "Please select a row to send the search patient");
//            return;
//        }

        Patient patient = (Patient) searchedPatientDatajTable.getValueAt(selectedRow, 0);
      //  int docId = patient.getPrimaryDocId();
        Employee doctor = null;
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            doctor = organization.getPersonDirectory().getEmployeeDirectory().searchEmp(patient.getPrimaryDocId()); 
            if(doctor != null) {
                break;
            }
        }

        doctor.getWorkQueue().getWorkRequestList().add(afp);  
        
        JOptionPane.showMessageDialog(null, "Request has been sent to " + doctor.getName());
        
    }//GEN-LAST:event_sendToDocjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable searchedPatientDatajTable;
    private javax.swing.JButton sendToDocjButton;
    // End of variables declaration//GEN-END:variables
}
